default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lab_locator_development
test:
  <<: *default
  database: lab_locator_test

production:
  <<: *default
  database: lab_locator_production
