Studio.create(name: "Starling Studios", website: "https://www.starlingrecording.com/", image_url: "https://images.unsplash.com/photo-1551710029-607e06bd45ff?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80", hourly_rate: 50, location: "Starling Studios,80 Congress St,Saratoga Springs,NY")
Studio.create(name: "Overit Studios", website: "https://overitstudios.com/", image_url: "https://images.unsplash.com/photo-1563330232-57114bb0823c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80", hourly_rate: 70 , location: "Overit Studios,435 New Scotland Ave,Albany,NY")
Studio.create(name: "Paramount Recording Studio", website: "http://paramountrecording.com/", image_url: "http://paramountrecording.com/wp-content/gallery/clients/switchfoot.jpg", hourly_rate: 250, location: "Paramount Recording Studio,6245 Santa Monica Blvd,Los Angeles,CA")
Studio.create(name: "The Brewery", website: "http://breweryrecording.com/", image_url: "https://breweryrecording.com/img/gallery/2.NYControlA_2.jpg", hourly_rate: 45, location: "The Brewery Recording Studio,1330 W 12th St,Los Angeles,CA")
Studio.create(name: "Patchwerk", website: "http://www.patchwerk.com/", image_url: "https://images.unsplash.com/photo-1563330232-57114bb0823c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80", hourly_rate: 65, location: "Patchwerk Recording Studios,1094 Hemphill Ave NW,Atlanta,GA")
Studio.create(name: "Blue South", website: "bluerecorders.com/", image_url: "https://images.unsplash.com/photo-1593697724191-f148e1bcd3c0?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80", hourly_rate: 90, location: "Blue South Recording Studios,500 Bishop St NW,Atlanta,GA")
Studio.create(name: "House Of Hits", website: "houseofhitsmiami.com", image_url: "https://mrmixandmaster.com/wp-content/uploads/2020/06/IMG_3947-1024x768.jpg", hourly_rate: 75, location: "House Of Hits Recording Studio,300 NE 75th St Unit 112,Miami,FL")
Studio.create(name: "Mix Masters", website: "http://live.vcita.com/site/mixmasters", image_url: "https://s3-media0.fl.yelpcdn.com/bphoto/Dih4RdTCypNNDpDC9fjtxg/l.jpg", hourly_rate: 80, location: "Mix Masters Studios,2648 NW 21st Terrace, Miami, FL")
Studio.create(name: "Barron Studios", website: "http://www.recordwithbarron.com/", image_url: "https://i4.ypcdn.com/blob/153df4657cb69a45f73184fc80b57d7ed868a8f6", hourly_rate: 50, location: "Barron Studios,1701 Detering St,Houston,TX")


User.create(username: "dyl", password: "password")